/*
* This source file was generated by the Gradle 'init' task
*/

package swing;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

public class App extends JFrame {

    public App() {
        setTitle("Project Sekai Characters");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLayout(new BorderLayout());
    
        CharacterData charGrid = new CharacterData(null, true); 
        JScrollPane scrollPane = new JScrollPane(charGrid);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getVerticalScrollBar().setUnitIncrement(32);

        JSplitPane splitPane = new JSplitPane();    
        splitPane.setDividerLocation(240);
        splitPane.setLeftComponent(new Sidebar(splitPane));
        splitPane.setRightComponent(scrollPane); 
        splitPane.setDividerSize(10); 

        splitPane.setUI(new BasicSplitPaneUI() {
            @Override
            public BasicSplitPaneDivider createDefaultDivider() {
                return new BasicSplitPaneDivider(this) {
                    @Override
                    public void setBorder(Border b) {
                    }

                    @Override
                    public void paint(Graphics g) {
                    }
                };
            }
        });
    
        add(new Navbar(), BorderLayout.NORTH);
        add(splitPane, BorderLayout.CENTER);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().setVisible(true);
        });
    }
}